services:
  rsync-centry:
    build: .
    container_name: rsync-centry
    ports:
      - "8856:8856"
    volumes:
      - "/vol1:/home:ro"
      - "/vol02:/data"
      - "./data:/app/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - LANG=zh_CN.UTF-8
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    stop_grace_period: 10s
